# This example uses YAML anchors which allows reuse of multiple keys 
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/d6114726d859df36ccaa32891c4963ae5717ef7f/nixos/.sops.yaml
# for a more complex example.
keys:
  - &fishy-retriever age18ev7rfr2lqf7jm3vt028jctjjw6962gzsnmj90wmglc7mews39vq6uwlje
  - &stinky-husky age1fu5x8gl2j9kre4sk9nwaw6ajytl7egvqwhujqdzgwqwehcy0ayhsmk3u6m
  - &flatten-collie age14vwc6swaz72uasvmt99ae5h22zxd2pjfk56jf3nzcr76cg3e5fgstdx8m6
creation_rules:
  - path_regex: secrets/shared.yaml$
    key_groups:
    - age:
      - *fishy-retriever
      - *stinky-husky
      - *flatten-collie
  - path_regex: secrets/hosts/fishy-retriever.yaml
    key_groups:
    - age:
      - *fishy-retriever
  - path_regex: secrets/hosts/stinky-husky.yaml
    key_groups:
    - age:
      - *stinky-husky
